name: Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev

permissions:
  actions: read
  contents: read

jobs:
  debug:
    uses: ./.github/workflows/debug.yml
    secrets: inherit
  deploy:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: artifact
          path: dist
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: fe3c29c45fd096d701ebf5b43f1e76b1
          gist_description: "ï£¿ iRingo: ðŸ“° ï£¿News Î²"
          file_path: dist/request.js
